# Generated by Django 6.1 on 2026-09-03 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biography", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={"verbose_name_plural": "About"},
        ),
    ]
