# Generated by Django 6.1 on 2026-08-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_blog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="categgory",
            new_name="category",
        ),
        migrations.AlterField(
            model_name="blog",
            name="featured_image",
            field=models.ImageField(upload_to="uploads/%y/%m/%d"),
        ),
    ]
